// Original, configurable global-theme slot definitions. The shared FestivalEngine
// supplies cryptographic server-side RNG and the base award evaluation.
export const GLOBAL_GAMES = {
  'marigold-outlaws': { id: 'marigold-outlaws', title: 'Marigold Outlaws', rows: 4, columns: 5, rtp: 0.965, feature: 'Serenata Selvagem', featureChance: 0.035, featureMultiplier: 5, payoutScale: 0.31, symbols: [{ key: 'tequila', glyph: '🍹', weight: 31, pays: 0.25 }, { key: 'maraca', glyph: '🪇', weight: 25, pays: 0.42 }, { key: 'guitar', glyph: '🎸', weight: 20, pays: 0.7 }, { key: 'cactus', glyph: '🌵', weight: 16, pays: 1.3 }, { key: 'outlaw', glyph: '💀', weight: 8, pays: 3.8 }] },
  'cloverwood-gold': { id: 'cloverwood-gold', title: 'Cloverwood Gold', rows: 6, columns: 6, rtp: 0.965, feature: 'Trilha do Arco-íris', featureChance: 0.03, featureMultiplier: 7, payoutScale: 0.13, symbols: [{ key: 'clover', glyph: '☘️', weight: 31, pays: 0.16 }, { key: 'horseshoe', glyph: '🧲', weight: 25, pays: 0.27 }, { key: 'pipe', glyph: '🚬', weight: 20, pays: 0.45 }, { key: 'pot', glyph: '🍯', weight: 16, pays: 0.85 }, { key: 'sprite', glyph: '🧝', weight: 8, pays: 2.7 }] },
  'lotus-sanctuary': { id: 'lotus-sanctuary', title: 'Lotus Sanctuary', rows: 3, columns: 5, rtp: 0.965, feature: 'Halo de Lótus', featureChance: 0.045, featureMultiplier: 6, payoutScale: 0.46, symbols: [{ key: 'spice', glyph: '🫙', weight: 31, pays: 0.27 }, { key: 'flower', glyph: '🌸', weight: 25, pays: 0.45 }, { key: 'lamp', glyph: '🪔', weight: 20, pays: 0.75 }, { key: 'idol', glyph: '🗿', weight: 16, pays: 1.4 }, { key: 'lotus', glyph: '🪷', weight: 8, pays: 4.0 }] },
  'stormwake-captain': { id: 'stormwake-captain', title: 'Stormwake Captain', rows: 3, columns: 5, rtp: 0.965, feature: 'Canhão da Maré', featureChance: 0.04, featureMultiplier: 5, payoutScale: 0.46, symbols: [{ key: 'map', glyph: '🗺️', weight: 31, pays: 0.27 }, { key: 'rum', glyph: '🍾', weight: 25, pays: 0.44 }, { key: 'compass', glyph: '🧭', weight: 20, pays: 0.74 }, { key: 'chest', glyph: '🧰', weight: 16, pays: 1.35 }, { key: 'captain', glyph: '🏴‍☠️', weight: 8, pays: 3.9 }] },
  'coral-wave-riders': { id: 'coral-wave-riders', title: 'Coral Wave Riders', rows: 4, columns: 5, rtp: 0.965, feature: 'Maré Solar', featureChance: 0.04, featureMultiplier: 4, payoutScale: 0.31, symbols: [{ key: 'shell', glyph: '🐚', weight: 31, pays: 0.25 }, { key: 'coconut', glyph: '🥥', weight: 25, pays: 0.43 }, { key: 'starfish', glyph: '⭐', weight: 20, pays: 0.7 }, { key: 'board', glyph: '🏄', weight: 16, pays: 1.3 }, { key: 'wave', glyph: '🌊', weight: 8, pays: 3.8 }] },
  'rune-fjord': { id: 'rune-fjord', title: 'Rune Fjord', rows: 6, columns: 6, rtp: 0.965, feature: 'Martelo do Céu', featureChance: 0.025, featureMultiplier: 9, payoutScale: 0.13, symbols: [{ key: 'axe', glyph: '🪓', weight: 31, pays: 0.16 }, { key: 'helmet', glyph: '⛑️', weight: 25, pays: 0.27 }, { key: 'horn', glyph: '📯', weight: 20, pays: 0.46 }, { key: 'rune', glyph: 'ᚱ', weight: 16, pays: 0.88 }, { key: 'longship', glyph: '⛵', weight: 8, pays: 2.8 }] },
  'gorgon-nightfall': { id: 'gorgon-nightfall', title: 'Gorgon Nightfall', rows: 3, columns: 5, rtp: 0.965, feature: 'Olhar de Ônix', featureChance: 0.035, featureMultiplier: 6, payoutScale: 0.46, symbols: [{ key: 'helmet', glyph: '⛑️', weight: 31, pays: 0.27 }, { key: 'mirror', glyph: '🪞', weight: 25, pays: 0.44 }, { key: 'dagger', glyph: '🗡️', weight: 20, pays: 0.74 }, { key: 'statue', glyph: '🗿', weight: 16, pays: 1.38 }, { key: 'gorgon', glyph: '🐍', weight: 8, pays: 4.0 }] },
  'shaolin-strikers': { id: 'shaolin-strikers', title: 'Shaolin Strikers', rows: 4, columns: 5, rtp: 0.965, feature: 'Chute do Dragão', featureChance: 0.035, featureMultiplier: 5, payoutScale: 0.31, symbols: [{ key: 'whistle', glyph: '📣', weight: 31, pays: 0.25 }, { key: 'boot', glyph: '👟', weight: 25, pays: 0.43 }, { key: 'goal', glyph: '🥅', weight: 20, pays: 0.71 }, { key: 'ball', glyph: '⚽', weight: 16, pays: 1.32 }, { key: 'monk', glyph: '🥋', weight: 8, pays: 3.9 }] },
  'lemur-fruit-caravan': { id: 'lemur-fruit-caravan', title: 'Lemur Fruit Caravan', rows: 3, columns: 5, rtp: 0.965, feature: 'Caixas da Selva', featureChance: 0.05, featureMultiplier: 4, payoutScale: 0.46, symbols: [{ key: 'melon', glyph: '🍉', weight: 31, pays: 0.27 }, { key: 'pineapple', glyph: '🍍', weight: 25, pays: 0.45 }, { key: 'banana', glyph: '🍌', weight: 20, pays: 0.75 }, { key: 'starfruit', glyph: '🍈', weight: 16, pays: 1.4 }, { key: 'lemur', glyph: '🐒', weight: 8, pays: 4.0 }] }
};
